### PR TITLE
add testExplorer.useNativeTesting setting

### PR DESCRIPTION
**Pull request by hbenl**

### CODE REVIEW

**Comment by hbenl** [comment]
@connor4312 Here's the PR for the changes [we talked about](https://github.com/hbenl/test-adapter-converter/issues/1#issuecomment-824466772).
I would suggest that you register/unregister your converter whenever the `testExplorer.useNativeTesting` flag changes.
By the way, you probably don't need to worry about missing events if you register the converter late: you will miss events for past test runs, but not those for loading the tests: when an adapter sends its test tree, the `TestHub` remembers it and when a controller registers later on, the `TestHub` will send "synthetic" load events containing the test tree to it.

**Comment by connor4312** [comment]
Thanks, looks good! I've updated the converter accordingly. Two things:

- It seems that running the command as part of activation gives us some difficulty, trying to access its exports synchronously in the command fails. I suggest adding 0ms `setTimeout` before calling the command inside of `activate`
- I would also suggest that hiding the extension Test Explorer view when `testExplorer.useNativeTesting` is on -- it could be useful for debugging, but for end users just results in duplicate explorer views

**Comment by hbenl** [comment]
I've just published this.
- the activation command is now delayed as suggested
- the Test Explorer view is hidden as suggested
- the commands are hidden from the command palette when the Test Explorer view is hidden (they are still registered, but I didn't see any harm in that)
- I have removed the extension dependency on your converter extension because VS Code doesn't allow circular extension dependencies. I suggest that you remove the Test Explorer dependency from your converter and I will then add the dependency again, because that dependency will be necessary to automatically migrate all Test Explorer users to native testing when I make `useNativeTesting` the default.

**Comment by connor4312** [comment]
Thanks! Realized I forgot to push the updates to the converter extension, I've now done so in 0.0.8

**Comment by TylerLeonhardt** [comment]
@hbenl I think you can re-add the extension dependency now. Right @connor4312?

**Comment by connor4312** [comment]
Yep

**Comment by hbenl** [comment]
@TylerLeonhardt Thanks for the reminder.

**Pull request merged**
