### PR TITLE
Remove jest adapter from README.md

### PR DESCRIPTION
**Pull request by pbotsman**
Related to #119

### CODE REVIEW

**Comment by SSmale** [comment]
[There is this fork that works but needs releasing to the marketplace, until then you'd have to install via VSIX](https://github.com/kavod-io/vscode-jest-test-adapter)

**Comment by pbotsman** [comment]
Ok, closing this PR then

**Comment by hbenl** [comment]
FYI: A new [Jest Test Explorer](https://marketplace.visualstudio.com/items?itemName=kavod-io.vscode-jest-test-adapter) extension (forked from the removed one) has been published to the marketplace.

**Comment by pbotsman** [comment]
@hbenl thanks!

**Pull request closed without merging**
